### ISSUE TITLE
Disconnects automatically after very short time

### ISSUE THREAD

**Issue by kdoggthebus** [localtunnel/localtunnel#120] opened 2016-05-01 16:14 UTC
No error is thrown, but my localtunnel disconnects automatically after an incredibly short period of inactivity. It seems to disconnect in under 1 min of inactivity - which makes it very difficult to develop with. Is there any way to disable/increase this timeout?

**Comment by tezlopchan** [comment] 2016-05-12 16:32
create as bash script like try.sh with 
```
#!/bin/bash
lt --subdomain testratesyapp --port 3000
```
and then run ```watch n30 ./try.sh``` so this runs the try.sh every 30 sec 
and it worked for me with a constant subdomain

**Comment by perqa** [comment] 2016-05-13 10:38
Duplicate of "the server is not running persistently #111"  https://github.com/localtunnel/localtunnel/issues/111

**Comment by si458** [comment] 2016-05-23 12:00
i did the following for my OSX with this issue
`#!/bin/bash
while :; 
  do 
  clear
  date
  /usr/local/bin/lt --subdomain (UR DOMAIN) --local-host 127.0.0.1 --port 80
  sleep 30
done`

**Comment by reorx** [comment] 2016-06-19 13:04
I use a crontab to restart it every 15m, works for me.

`*/15 * * * * cd /home/work/supervisor && supervisorctl restart localtunnel`

**Comment by HasanY1989** [comment] 2016-08-08 13:30
Can some 1 explain me how to do this?

**Comment by sergeyganago** [comment] 2016-08-12 01:30
And author thinks this is better than ngrok???

**Comment by defunctzombie** [comment] 2016-11-27 18:08
> And author thinks this is better than ngrok???

@sergeyganago relax, Where do you see me saying it is better than ngrok or forcing anyone to use this? I made this project because I had a random idea on how to do local server exposure with nodejs, that's it. Please take your negative shit comments elsewhere.

**Closed by defunctzombie** 2016-11-27 18:08 UTC

**Comment by ptaking** [comment] 2017-11-07 07:35
> And author thinks this is better than ngrok???
For free users: Yes. I'm creating a messenger bot and it needs a persistent url.

**Comment by ptaking** [comment] 2017-11-07 07:37
@si458 I don't think your script will check for anything. It just simple do what `watch` do. Run `lt` every 30 secs
