### ISSUE TITLE
No HTTPS

### ISSUE THREAD

**Issue by AsalhiOfficial** [localtunnel/localtunnel#512] opened 2022-07-22 02:55 UTC
Hi. It seems there may be something wrong with the ssl certificate as https is not working.

**Comment by stfsy** [comment] 2022-07-22 09:15
+1 The certificate is only valid for localtunnel.me and not for *.loca.lt

**Comment by suryarocks11** [comment] 2022-07-22 13:36
Yes, the HTTPS not working after the server restarted.
NET::ERR_CERT_COMMON_NAME_INVALID

**Comment by parkcoop** [comment] 2022-07-22 14:13
Yes the only workaround is to remove https but this may not be ideal for a lot of people

**Comment by steezeburger** [comment] 2022-07-22 18:35
I'm trying to develop a webhook that requires https, so I'm unfortunately dead in the water.

**Comment by jeffersonlicet** [comment] 2022-07-28 21:02
Can we help get a better cert?

**Comment by tehg00se** [comment] 2022-07-30 11:03
plz help

**Comment by BrennerSpear** [comment] 2022-08-01 15:01
Also causing issues for me, I need https for what I'm testing

**Comment by joshuakcockrell** [comment] 2022-08-03 13:45
This is a BAD issue. I don't see a single open issue in this repo with the number of upvotes as this one in the last 2 years.

Looks like this is the maintainer that's set up the current `loca.lt` stuff https://github.com/localtunnel/localtunnel/issues/347#issuecomment-687675533

**Comment by TheBoroer** [comment] 2022-08-03 14:26
## @Everyone
Hey all! I'm back from my vacation, sorry for this https mess. I think I've fixed it for good.
I'll close this issue once a couple of you confirm it's all working now :)

### The problem
Setup:
- I had a certbot running to do http challenges for the `localtunnel.me` (since I don't control that domain and just got an A record for the root domain pointed at me).
- I also had a `dnsrobocert` container running to do the dns challenge for `*.loca.lt` in order to get a wildcard cert for all the localtunnel subdomain.
- both containers save to the same letsencrypt folder so that my reverse proxy can pick the certs up and auto-configure ssl and routing.

The two seemed to have worked well together when I initially tried it way back when so I just left it running as is. After some downtime and random server restarts, I guess my luck ran out since now the two cert renewal services were conflicting with each other (and should have been from the start). dnsrobocert apparently deletes and revokes any certs it sees that it's not configured for (aka `localtunnel.me`). The http certbot process would then renew but then do something funky with the wildcard cert (idk exactly what, maybe force renew it and fail)? Fast forward to 1-2 weeks ago, both the certbot processes were hammering letsencrypt with renew and revoke requests....ending up with us hitting the cert limit for that week. We had wait a week for the cert rate limit to be reset and let us get certs again.

### Solution
I reworked my docker container setup. Since I can't configure `dnsrobocert` to ignore/avoid revoking certs it isn't configured for, I decided to switch over to using the standard certbot container. I'm hoping this setup won't break for a longggg time. Both dns and http challenge containers seem to be behaving atm, they're only looking and renewing the certs they're tasked to handle.

As a bonus, i've just written a manual config file for `*.loca.lt` instead of letting my reverse proxy auto configure itself for this service.

Sorry any inconvenience, I really thought my setup was perfect before lol. Hopefully this is the last time we'll have cert issues on this service. 😅

**Comment by stfsy** [comment] 2022-08-03 14:41
Thanks for the update @TheBoroer. Glad you're back and glad you were able to be on vacation without duties like this one!

**Comment by joshuakcockrell** [comment] 2022-08-03 21:09
Whew. Thanks for fixing this. I was down a 2 hour black hole of trying to figure out how to deploy my own localtunnel server to AWS 😅

I can confirm https is back and working again.

**Comment by TheBoroer** [comment] 2022-08-05 17:14
haha yayy! I'll go ahead and close this issue, thanks for confirming everyone! :)

@joshuakcockrell darn, sorry about that. Having a one-click heroku deploy button has been on my todo list for ages. I'll try to write up a small docker deployement tutorial write up when I get some free time but I won't have an ETA for it right now.

**Closed by TheBoroer** 2022-08-05 17:14 UTC

**Comment by BrennerSpear** [comment] 2022-08-07 23:53
If you wanna try railway.app (which actually uses heroku), it's an even easier setup (not affiliated, just a user of it and I like it)
