### ISSUE TITLE
localtunnel Currently Offline

### ISSUE THREAD

**Issue by biscuits4cheese** [localtunnel/localtunnel#503] opened 2022-06-23 20:23 UTC
localtunnel is currently offline.  The npm command with a named subdomain just hangs.

Causing me a major problem.

Any update to the cause or further information please?

**Comment by henk717** [comment] 2022-06-23 21:14
Confirmed in #501

**Comment by RolandSall** [comment] 2022-06-24 07:17
any updates?

**Comment by amm13** [comment] 2022-06-24 09:53
Same here

**Comment by biscuits4cheese** [comment] 2022-06-24 09:59
I _really_ hope this is not the end of this service.  It's free and just so easy to use!

**Comment by deepaksinghsolanki1989** [comment] 2022-06-25 07:17
Any working alternative apart from Ngrok

**Comment by suryarocks11** [comment] 2022-06-25 19:00
its still not up.. :(

**Comment by daniielsantos** [comment] 2022-06-26 03:29
F

**Comment by DavertMik** [comment] 2022-06-26 19:56
Still

**Comment by igortavtib** [comment] 2022-06-26 22:33
same here, waiting for any update

**Comment by sacch6579** [comment] 2022-06-27 03:23
Anyway we can replicate the service elsewhere?

**Comment by chiragramjibhaipatel** [comment] 2022-06-27 04:52
any alternative or workaround for this problem?

**Comment by BashardinhoGitHube** [comment] 2022-06-27 05:32
I feel that all open source software are getting tired.

we need to give more than we take so that the world would be a better place.

**Comment by deepdil-sp** [comment] 2022-06-27 07:42
any change or update ?

**Comment by iBeizsley** [comment] 2022-06-27 11:42
> Anyway we can replicate the service elsewhere?


> Anyway we can replicate the service elsewhere?

It can be self-hosted: https://github.com/localtunnel/server

**Comment by umobiajulu** [comment] 2022-06-27 16:22
i have been able to replicate it on https://stunel.io for my apps that depend on it

**Comment by Ehbraheem** [comment] 2022-06-27 19:54
> i have been able to replicate it on https://stunel.io for my apps that depend on it. the only thing that works now is npm install, i have not published it on yarn yet

@iBeizsley @sacch6579 Let's give this a try

**Comment by umobiajulu** [comment] 2022-06-28 07:00
> i have been able to replicate it on https://stunel.io for my apps that depend on it. the only thing that works now is npm install, i have not published it on yarn yet

why did google mark my site as harmful, i don't get it

**Comment by biscuits4cheese** [comment] 2022-06-28 07:39
@angelhodar Thanks for this.  I'm more than interested! Can't believe I missed this trying to find alternatives. Again, thanks very much.

**Comment by umobiajulu** [comment] 2022-06-28 11:17
> i have been able to replicate it on https://stunel.io for my apps that depend on it. the only thing that works now is npm install, i have not published it on yarn yet

Previouly, when your clients disconnects from the server, it will be difficult for you to connect to the same subdomain. This can last for hours or days before you get access to the subdomain, meanwhile no one else is using the sundomain. I have solved the problem by introducing passworded request. Each request of subdomain will be done with a password, if the same password is used for another request for the same subdomain, the server will kill the previous client with and give access to the new client

**Comment by KangLeian** [comment] 2022-06-30 03:01
> > i have been able to replicate it on https://stunel.io for my apps that depend on it. the only thing that works now is npm install, i have not published it on yarn yet
> 
> Previouly, when your clients disconnects from the server, it will be difficult for you to connect to the same subdomain. This can last for hours or days before you get access to the subdomain, meanwhile no one else is using the sundomain. I have solved the problem by introducing passworded request. Each request of subdomain will be done with a password, if the same password is used for another request for the same subdomain, the server will kill the previous client with and give access to the new client

I've been try use stunel but it goes something not secure. 
![image](https://user-images.githubusercontent.com/62584211/176583453-891d6bb2-8794-41a5-bab2-acdaebfadcc2.png)

Any advance for this?

**Comment by umobiajulu** [comment] 2022-06-30 04:47
Yeah google marked it as social engineering deceptive site so I added that warning so they can remove it. But you can click on continue button to proceed to the website. That page only shows when you access the tunnel through browser get request. APIs won't be directed to that page

**Comment by umobiajulu** [comment] 2022-06-30 04:57
So you can turn off your safe browsing protection whenever you want to use it until Google rectify approve the removal of the red deceptive page warning

**Comment by henk717** [comment] 2022-06-30 11:49
@umobiajulu I could not find the information behind the warning setup. I have been considering hosting my own for my users with a customized warning that basically asks them if they intend to use our software and only let them trough if they click yes. But i can't find the setup that boroer and you did anywhere. Would you like to share it with us? Because without it hosting this is impossible as you noticed as they immediately throw you on a block.

**Comment by umobiajulu** [comment] 2022-06-30 13:49
> @umobiajulu I could not find the information behind the warning setup. I have been considering hosting my own for my users with a customized warning that basically asks them if they intend to use our software and only let them trough if they click yes. But i can't find the setup that boroer and you did anywhere. Would you like to share it with us? Because without it hosting this is impossible as you noticed as they immediately throw you on a block.

or better still we can use google meet, i will be available tomorrow anytime from 12:00pm GMT+1 till 5:00pm GMT+1

**Comment by umobiajulu** [comment] 2022-06-30 14:33
> > > > > i have been able to replicate it on https://stunel.io for my apps that depend on it. the only thing that works now is npm install, i have not published it on yarn yet
> > > > 
> > > > 
> > > > Previouly, when your clients disconnects from the server, it will be difficult for you to connect to the same subdomain. This can last for hours or days before you get access to the subdomain, meanwhile no one else is using the sundomain. I have solved the problem by introducing passworded request. Each request of subdomain will be done with a password, if the same password is used for another request for the same subdomain, the server will kill the previous client with and give access to the new client
> > > 
> > > 
> > > I've been try use stunel but it goes something not secure. ![image](https://user-images.githubusercontent.com/62584211/176583453-891d6bb2-8794-41a5-bab2-acdaebfadcc2.png)
> > > Any advance for this?
> > 
> > 
> > this has been resolved, google finally heared my plea
> 
> Thanks for doing this. But there is an issue with the code. Previously I used it on a server whose server time was 3 months back due for some reason. Now Whenever I am trying your tunnel It's not working. In lt, i used to use this command. lt -p 4400 -s cotest2022

what was the command you used on stunel

**Comment by TheBoroer** [comment] 2022-06-30 19:50
FYI, localtunnel is back up now :)

**Closed by TheBoroer** 2022-06-30 19:50 UTC
