### ISSUE TITLE
Local tunnel didn't work properly

### ISSUE THREAD

**Issue by Saylion** [localtunnel/localtunnel#628] opened 2023-10-22 06:28 UTC
I've tried to set my local into public with local tunnel use this code
`
import subprocess
import threading
import time
import socket
import urllib.request
def iframe_thread(port):
    while True:
        time.sleep(0.5)
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        result = sock.connect_ex(('127.0.0.1', port))
        if result == 0:
            break
        sock.close()
        
        from colorama import Fore, Style
    print(Fore.GREEN + "\nLocaltunnel Endpoint IP is:", Fore.RED, urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip("\n"),"\n",Style.RESET_ALL)
    p = subprocess.Popen(["lt", "--port", "{}".format(port)], stdout=subprocess.PIPE)
    for line in p.stdout:
        print(line.decode(), end='')
threading.Thread(target=iframe_thread, daemon=True, args=(7860,)).start()
`

But the public link didn't appear. How is this?

**Comment by H1ghN0on** [comment] 2023-10-22 12:40
same, worked fine before

**Comment by mkyc** [comment] 2023-10-22 12:47
Maybe that is because of expired ssl certificate?

**Comment by os1ma** [comment] 2023-10-22 13:47
I've had the same problem since yesterday. The expired certificate of localtunnel.me might be the cause.

**Comment by briankariuki** [comment] 2023-10-22 21:16
Did anyone find a solution?

**Comment by Saylion** [comment] 2023-10-23 01:23
> Did anyone find a solution?

How about py-localtunnel or try cloudflare, but I can't implementing on code like that

**Comment by Parking-Master** [comment] 2023-10-23 20:44
Try using serveo in the meantime.
The server goes down quite a lot but I recommend it for personal use or quick access to your server(s).

```
ssh -R yoursubdomain.serveo.net:80:localhost:8080 serveo.net
```

Replace "yoursubdomain" and "8080" with your custom subdomain and port.

**Comment by Parking-Master** [comment] 2023-11-01 03:34
Duplicate of #630. You can close this issue now.

**Closed as completed** 2023-11-04 02:07 UTC
