### ISSUE TITLE
localtunnel.me SSL Certificate Expired

### ISSUE THREAD

**Issue by bartoszkwiedacz** [localtunnel/localtunnel#334] opened 2019-12-13 10:57 UTC
The ssl certificate for localtunnel.me has expired 11.12.2019. None of secure localtunnel doesn't work.

**Comment by WBDC** [comment] 2019-12-13 12:22
> The ssl certificate for localtunnel.me has expired 11.12.2019. None of secure localtunnel doesn't work.

Please close this ticket as it is a duplicate of #332

**Closed** 2019-12-17 16:00 UTC
