### ISSUE TITLE
`window.ethereum.selectedAddress` error displaying on mobile device while running localtunnel

### ISSUE THREAD

**Issue by dillonstreator** [localtunnel/localtunnel#514] opened 2022-07-27 01:35 UTC
iPhone 13 with Brave browser - no extensions installed.
This started today and is only happening on my phone. This issue does not exist with ngrok.

Could this mean loca.it servers are compromised?

![lterror](https://user-images.githubusercontent.com/26043866/181140178-e17b96fe-003e-4c64-95f9-54b7896b0180.png)

**Comment by TheBoroer** [comment] 2022-07-27 10:07
Hey! Nope, loca.lt server isn't compromised. 

Are there any other errors in the console? Does Brave browser for mobile with no extension even have a web3 wallet built into it to? I thought it doesn't and that you'd have to use brave wallet or something else?

**Comment by DillonStreator** [comment] 2022-07-27 12:20
@TheBoroer Nope to all.

The main concern here is that the issue is no longer present just by switching the tunneling service to ngrok.

**Comment by TheBoroer** [comment] 2022-07-27 13:14
Hmm, can you please whip up a simple test repo for me so i can reproduce and troubleshoot this?

**Comment by DeclanCrane** [comment] 2023-01-17 05:52
It has something to do with an outdated API the Brave browser uses.

**Comment by TheBoroer** [comment] 2023-01-17 16:35
I'm closing this since it's not a localtunnel related issue

**Closed by TheBoroer** 2023-01-17 16:35 UTC

**Comment by architchandra** [comment] 2023-09-07 11:22
I'm facing the same issue. Were you able to figure this out @dillonstreator?

**Comment by BernhardBehrendt** [comment] 2024-01-04 00:01
I'm facing the same issue. 
Only on Brave on iOS.
In my case I'm accessing a next.js app over my network. 
Nothing like that happens when I call it in browser nor via ios safari
![Bildschirmfoto 2024-01-04 um 00 58 35](https://github.com/localtunnel/localtunnel/assets/1717382/f2e9b584-5908-4ec5-92c1-df2514707510)

**Comment by amityweb** [comment] 2024-04-19 09:18
I am here as I have this all of a sudden, BUT I cant see this being an issue with localtunnel... I am not using localtunnel. I am just connecting to my computers local IP on Node port 3000, in Brave browser on the phone, and I get the issue.

For me, I am using Geo lookup based on IP address from Maxmind. Connecting to a local computer does not give my code any suitable IP to lookup so is returning unknown. So this is the issue for me, and not localtunnel.

I am posting this here because its a top link on search results and people are still asking about it the error here after its a closed issue and nothing to do with localtunnel. 

I'm also now going to check localtunnel out anyway, I was thinking about how to do this just yesterday!

**Comment by TheBoroer** [comment] 2024-04-19 18:49
Thanks for chiming in on this @amityweb and welcome to localtunnel :)

I actually was wondering why this non-localtunnel issue kept bringing people here, I didn't realilze that it's the first result on google when searching for the error (and the brave-ios repo is the second result) haha.

**Comment by jonathanpv** [comment] 2025-07-22 04:02
ran into this as well, its a brave issue, they do have crypto related stuff for rewards
