### ISSUE TITLE
loca.lt DOWN?

### ISSUE THREAD

**Issue by mr-mmmmore** [localtunnel/localtunnel#478] opened 2022-03-02 09:41 UTC
This morning it seems that the server has a problem: while refreshing the url through the loca.lt url I get errors most of the time:

- A 404 page error (but it is actually the good response from my server for the url I test)
- A 500 internal server error (which doesn't occur on my local server, I've checked the logs)
- A PR_END_OF_FILE_ERROR Secure connexion error

I use localtunnel to debug a local Stripe Webhook and events send by Stripe fail with a TLS error. Earlier this morning the events were working OK and then it has started to fail and never worked again.

Here the command that I've been using for months:
`lt --port 80 --subdomain mypublicsubdomain --local-host mylocal.domain.loc`

**Comment by jjtindale** [comment] 2022-03-02 11:19
We were having similar issues, but it seems to have resolved itself now.

**Comment by mr-mmmmore** [comment] 2022-03-02 12:29
Yes it has worked for a few hours after my message but it is broken again.

**Comment by TheBoroer** [comment] 2022-03-02 19:41
Hey all! Could you please test out the server again? It seemed to be caused by the nginx reverse proxy sitting in front of the localtunnel server...no clue why it was happening, a good ol' restart seems to have fixed it.

**Comment by fstrube** [comment] 2022-03-02 20:38
I'm still having similar issues, which have been ongoing since yesterday or the day before.

**Comment by fstrube** [comment] 2022-03-02 20:48
FWIW, https://localtunnel.me is also exhibiting intermittent 500 errors.

**Comment by RebeccaStankus** [comment] 2022-03-02 21:06
I just started having this issue a couple hours ago. I can't use lt at all right now.

**Comment by nucleiis** [comment] 2022-03-03 08:05
I am having issues again at this moment

**Comment by nucleiis** [comment] 2022-03-03 08:08
Seems like 500 error is back again

**Comment by flyingboy007** [comment] 2022-03-06 20:19
I am also having these intermittent 500 errors for last couple of days

**Comment by shayas** [comment] 2022-03-08 10:10
500 error also for me

**Comment by sauntimo** [comment] 2022-03-08 12:37
is local tunnel being patchy for anyone else today? I'm serving an dev slack chat bot through it and several slack messages have had to be re-tried several times because they weren't able to verify the ssl cert - weird though, because the certificate looks good, so maybe that error is misleading.

```
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.loca.lt
*  start date: Feb 26 03:29:46 2022 GMT
*  expire date: May 27 03:29:45 2022 GMT
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7feb14012400)
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
```

**Comment by andreperegrina** [comment] 2022-03-08 17:49
I'm having the same issue as @sauntimo

**Comment by 300Gram** [comment] 2022-03-08 18:59
Soooo. This is the reason why it's causing my webhook POST request not coming into my server.... 

Some time it works for a good few hours and then go down. Now it's completely dead. god damn it.

**Comment by RebeccaStankus** [comment] 2022-03-08 21:56
yep, dead for me too now.

**Comment by TheBoroer** [comment] 2022-03-09 19:56
Are you guys still getting intermittent 500s or can't connect at all? I've just restarted all services on the server. 

The only change I've done recently to the public server is added a rate limit for new lt client connection requests (when you first run the command requesting for a specific or random subdomain). 

That change shouldn't have broke anything except if you're using a script to constantly poll the server for a specific subdomain, in which case you'll get hit with a 429 error when turning out verbose output on the `lt` client.

I can't seem to reproduce any of the errors except I was once seeing the intermittent 500s. I'm no longer getting those at the moment.

## RE: `PR_END_OF_FILE_ERROR Secure connection error`
I can't reproduce this one either. Whoever's experiencing this error, do you have DNS over HTTPS turned on or some antivirus web filtering running on the pc? Some bad people are trying to run phishing portals on the public server and maybe the entire loca.lt domain is being flagged for malicious use by AV software -_-

**Comment by TheBoroer** [comment] 2022-03-09 20:22
@sauntimo could you please paste a full/more complete curl response (you can take out anything sensitive)?
I don't think it's an issue with the actual localtunnel/loca.lt cert but probably either your ISP or antivirus or firewall filtering something. I'm interested in seeing if your curl is trying to connect to the right localtunnel server ip which is currently `193.34.76.44`.

**Comment by TheBoroer** [comment] 2022-03-09 21:19
# UPDATE 2:
So I think I narrowed this issue down to only happening when the lt client is used with the `--local-host` command argument (explains why I wasn't seeing the issue initially). 

When that cmd arg is used, the tunnel sockets randomly die on every incoming page request until the tunnel to have zero available sockets left then the tunnel requests hang until the nginx reverse proxy times out (that's when you'll get the 504 error). I'll have to keep digging to find out extactly why sockets are dying and not being re-established right away like they are when the command is run without `--local-host`

**Comment by sauntimo** [comment] 2022-03-10 09:53
@TheBoroer Here's a more complete curl response, hopefully it's helpful. However, I run my local tunnel with `lt --port 8080 --subdomain [mysubdomain] --print-requests`, I don't use the `--local-host` flag, and I was still having issues yesterday. That being said, it seems to be working ok today!

```
➜  ~ curl -kvI https://[mysubdomain].loca.lt/health-check
*   Trying 193.34.76.44:443...
* Connected to [mysubdomain].loca.lt (193.34.76.44) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.loca.lt
*  start date: Feb 26 03:29:46 2022 GMT
*  expire date: May 27 03:29:45 2022 GMT
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fa29f80e200)
> HEAD /health-check HTTP/2
> Host: [mysubdomain].loca.lt
> user-agent: curl/7.77.0
> accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200
HTTP/2 200
< server: nginx/1.17.9
server: nginx/1.17.9
< date: Thu, 10 Mar 2022 09:38:37 GMT
date: Thu, 10 Mar 2022 09:38:37 GMT
< content-type: application/json; charset=utf-8
content-type: application/json; charset=utf-8
< content-length: 34
content-length: 34
< x-powered-by: Express
x-powered-by: Express
< vary: Origin
vary: Origin
< etag: W/"22-UeKz70QMwQtfie5Non1AjoAq5Y8"
etag: W/"22-UeKz70QMwQtfie5Non1AjoAq5Y8"
< x-robots-tag: noindex, nofollow, noarchive, nosnippet, nositelinksearchbox, noimageindex
x-robots-tag: noindex, nofollow, noarchive, nosnippet, nositelinksearchbox, noimageindex
< localtunnel-agent-ips: ["137.220.70.142"]
localtunnel-agent-ips: ["137.220.70.142"]
```
I ran my local tunnel in debug mode and generated a few slack events to see what would happen, here's the out put from that:

```
➜  ~ DEBUG=localtunnel:client lt --port 8080 --subdomain [mysubdomain]
  localtunnel:client got tunnel information {
  id: '[myId]',
  port: 39893,
  max_conn_count: 10,
  url: 'https://[mysubdomain].loca.lt'
} +0ms
  localtunnel:client establishing tunnel http://localhost:8080 <> localtunnel.me:39893 +0ms
  localtunnel:client establishing tunnel http://localhost:8080 <> localtunnel.me:39893 +1ms
  localtunnel:client establishing tunnel http://localhost:8080 <> localtunnel.me:39893 +0ms
  localtunnel:client establishing tunnel http://localhost:8080 <> localtunnel.me:39893 +0ms
  localtunnel:client establishing tunnel http://localhost:8080 <> localtunnel.me:39893 +0ms
  localtunnel:client establishing tunnel http://localhost:8080 <> localtunnel.me:39893 +0ms
  localtunnel:client establishing tunnel http://localhost:8080 <> localtunnel.me:39893 +0ms
  localtunnel:client establishing tunnel http://localhost:8080 <> localtunnel.me:39893 +1ms
  localtunnel:client establishing tunnel http://localhost:8080 <> localtunnel.me:39893 +0ms
  localtunnel:client establishing tunnel http://localhost:8080 <> localtunnel.me:39893 +0ms
your url is: https://[mysubdomain].loca.lt
  localtunnel:client tunnel open [total: 1] +181ms
  localtunnel:client connecting locally to http://localhost:8080 +177ms
  localtunnel:client tunnel open [total: 2] +1ms
  localtunnel:client connecting locally to http://localhost:8080 +1ms
  localtunnel:client tunnel open [total: 3] +0ms
  localtunnel:client connecting locally to http://localhost:8080 +0ms
  localtunnel:client tunnel open [total: 4] +0ms
  localtunnel:client connecting locally to http://localhost:8080 +0ms
  localtunnel:client tunnel open [total: 5] +0ms
  localtunnel:client connecting locally to http://localhost:8080 +0ms
  localtunnel:client tunnel open [total: 6] +1ms
  localtunnel:client connecting locally to http://localhost:8080 +1ms
  localtunnel:client tunnel open [total: 7] +0ms
  localtunnel:client connecting locally to http://localhost:8080 +0ms
  localtunnel:client tunnel open [total: 8] +0ms
  localtunnel:client connecting locally to http://localhost:8080 +0ms
  localtunnel:client tunnel open [total: 9] +1ms
  localtunnel:client connecting locally to http://localhost:8080 +1ms
  localtunnel:client tunnel open [total: 10] +0ms
  localtunnel:client connecting locally to http://localhost:8080 +0ms
  localtunnel:client connected locally +0ms
  localtunnel:client connected locally +0ms
  localtunnel:client connected locally +0ms
  localtunnel:client connected locally +1ms
  localtunnel:client connected locally +0ms
  localtunnel:client connected locally +0ms
  localtunnel:client connected locally +0ms
  localtunnel:client connected locally +0ms
  localtunnel:client connected locally +0ms
  localtunnel:client connected locally +0ms
  localtunnel:client local connection closed [false] +46s
  localtunnel:client remote close +66ms
  localtunnel:client tunnel dead [total: 9] +46s
  localtunnel:client establishing tunnel http://localhost:8080 <> localtunnel.me:39893 +0ms
  localtunnel:client tunnel open [total: 10] +87ms
  localtunnel:client connecting locally to http://localhost:8080 +87ms
  localtunnel:client connected locally +0ms
  localtunnel:client local connection closed [false] +496ms
  localtunnel:client remote close +87ms
  localtunnel:client tunnel dead [total: 9] +583ms
  localtunnel:client establishing tunnel http://localhost:8080 <> localtunnel.me:39893 +0ms
  localtunnel:client tunnel open [total: 10] +106ms
  localtunnel:client connecting locally to http://localhost:8080 +106ms
  localtunnel:client connected locally +1ms
  localtunnel:client local connection closed [false] +18s
  localtunnel:client remote close +82ms
  localtunnel:client tunnel dead [total: 9] +18s
  localtunnel:client establishing tunnel http://localhost:8080 <> localtunnel.me:39893 +0ms
  localtunnel:client tunnel open [total: 10] +90ms
  localtunnel:client connecting locally to http://localhost:8080 +90ms
  localtunnel:client connected locally +1ms
  localtunnel:client local connection closed [false] +422ms
  localtunnel:client remote close +86ms
  localtunnel:client tunnel dead [total: 9] +509ms
  localtunnel:client establishing tunnel http://localhost:8080 <> localtunnel.me:39893 +0ms
  localtunnel:client tunnel open [total: 10] +89ms
  localtunnel:client connecting locally to http://localhost:8080 +89ms
  localtunnel:client connected locally +1ms
  localtunnel:client local connection closed [false] +7s
  localtunnel:client remote close +83ms
  localtunnel:client tunnel dead [total: 9] +7s
  localtunnel:client establishing tunnel http://localhost:8080 <> localtunnel.me:39893 +0ms
  localtunnel:client tunnel open [total: 10] +87ms
  localtunnel:client connecting locally to http://localhost:8080 +87ms
  localtunnel:client connected locally +1ms
  localtunnel:client local connection closed [false] +578ms
  localtunnel:client remote close +85ms
  localtunnel:client tunnel dead [total: 9] +664ms
  localtunnel:client establishing tunnel http://localhost:8080 <> localtunnel.me:39893 +0ms
  localtunnel:client tunnel open [total: 10] +88ms
  localtunnel:client connecting locally to http://localhost:8080 +88ms
  localtunnel:client connected locally +1ms
```

**Comment by mr-mmmmore** [comment] 2022-03-11 18:58
> So I think I narrowed this issue down to only happening when the lt client is used with the --local-host command argument (explains why I wasn't seeing the issue initially).

I don't use the --local-host parameter and have been affected by this issue since I created the ticket...

**Comment by TheBoroer** [comment] 2022-03-18 17:14
Thanks for posting more debug logs @sauntimo !
This is a weird one, so you're not using the `--local-host`flag and your debug logs look fine to me.

Random question, how long does your health check endpoint take to respond? is it instant or is there a range like 1-5 seconds?

**Comment by sauntimo** [comment] 2022-03-18 17:22
@TheBoroer ah, no it's instant, it just returns immediately. I don't know if this is relevant or not, but I find that my local tunnel process crashes, I would guess 10-20x per week and then I have to restart it. I have the command aliased to `_lt` for convenience. As far as I can tell, this generally happens when it's idle rather than as a result of a particular request - but it doesn't necessarily seem to be just when it's idle for a long time. For instance, some times the process will happily run over night and still be up the next morning, where as sometimes it will die while I'm working on something and it'll take me a minute to work out why my slack app isn't responding 😆 

```
Wed Mar 16 2022 16:18:34 GMT+0000 (Greenwich Mean Time) POST /slack/events
Wed Mar 16 2022 16:18:34 GMT+0000 (Greenwich Mean Time) POST /slack/events
/Users/tim/.config/yarn/global/node_modules/localtunnel/bin/lt.js:81
    throw err;
    ^

Error: connection refused: localtunnel.me:37687 (check your firewall settings)
    at Socket.<anonymous> (/Users/tim/.config/yarn/global/node_modules/localtunnel/lib/TunnelCluster.js:52:11)
    at Socket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
➜  ~ _lt
your url is: https://[my-domain].loca.lt
/Users/tim/.config/yarn/global/node_modules/localtunnel/bin/lt.js:81
    throw err;
    ^

Error: connection refused: localtunnel.me:41659 (check your firewall settings)
    at Socket.<anonymous> (/Users/tim/.config/yarn/global/node_modules/localtunnel/lib/TunnelCluster.js:52:11)
    at Socket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
➜  ~ _lt
your url is: https://[my-domain].loca.lt
/Users/tim/.config/yarn/global/node_modules/localtunnel/bin/lt.js:81
    throw err;
    ^

Error: connection refused: localtunnel.me:46137 (check your firewall settings)
    at Socket.<anonymous> (/Users/tim/.config/yarn/global/node_modules/localtunnel/lib/TunnelCluster.js:52:11)
    at Socket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
➜  ~ _lt
your url is: https://[my-domain].loca.lt
Fri Mar 18 2022 16:12:56 GMT+0000 (Greenwich Mean Time) POST /slack/events
Fri Mar 18 2022 16:12:57 GMT+0000 (Greenwich Mean Time) POST /slack/events
Fri Mar 18 2022 16:12:58 GMT+0000 (Greenwich Mean Time) POST /slack/events
Fri Mar 18 2022 16:25:36 GMT+0000 (Greenwich Mean Time) POST /slack/events
Fri Mar 18 2022 16:25:37 GMT+0000 (Greenwich Mean Time) POST /slack/events
```

**Comment by zhaytee** [comment] 2022-03-18 21:21
I'm also experiencing issues, mostly TLS errors. Until now, I haven't encountered any connectivity issues in over a year of using the loca.lt service.

Great service in general btw. It's a shame that I've only gotten around to expressing my gratitude at a time like this when there's a problem. 😄  Would definitely support this project financially if such a thing were on offer.

**Comment by fandy** [comment] 2022-04-01 15:17
Still down right now :*(

**Comment by uzza1hossain** [comment] 2022-04-04 18:58
Not working. Same issue happening for days

**Comment by HackerDaGreat57** [comment] 2022-05-10 04:35
Fixed I think lol, close this issue plz

**Comment by Kikobeats** [comment] 2022-05-16 23:08
It's working to me – something changed?

**Comment by argough** [comment] 2022-06-23 14:50
Down again today

**Comment by MorenoMdz** [comment] 2022-06-23 15:40
Down again haha

**Comment by devwithzachary** [comment] 2022-06-27 14:35
Seems to be down for me as well

**Comment by harsha173** [comment] 2022-06-28 07:26
is there any solution for it loca.it service to work again

**Comment by kdrkdrkdr** [comment] 2022-07-02 09:55
localtunnel is back!
![image](https://user-images.githubusercontent.com/49074597/176995668-c358934a-0107-4713-8141-16d25b42edd7.png)

**Comment by wcoder** [comment] 2022-07-10 23:06
Host sometimes down:
<img width="456" alt="Screen Shot 2022-07-11 at 2 05 09 AM" src="https://user-images.githubusercontent.com/766193/178165499-f396fb0b-fc36-40de-82fd-cec9dde46e1a.png">

**Comment by TheBoroer** [comment] 2022-08-03 14:31
Hey all, we had some issues with the localtunnel public server over the last few weeks.

I think everything's back up and running how it should, so i'll be closing this issue. Feel free to @ me if the issue still is happening and I'll re-open it again.

**Closed by TheBoroer** 2022-08-03 14:31 UTC

**Comment by radwanHb** [comment] 2022-09-03 18:59
@TheBoroer  hi friend  🙌  ..... today i face a ( 500 Internal Server Error ) when sending image files to local server running lt , any help please !
thanks

**Comment by Le-web-developpeur1** [comment] 2025-03-20 15:12
Bonjour à tous ! 
Je suis Boubacar Bah, actuellement en formation au développement web et mobile Chez Simplon Guinée.  Il y'a de cela 4 mois maintenant. Et on travaille sur un projet, où quand un utilisateur est ajouté, il reçoit un mail avec un lien lui permettant de définir un mot de passe.
Et j'ai utilisé localtunnel pour tester si celà va marcher mais depuis plus de trois jours, je reçois toujours aussi cela : Failed to load resource: the server responded with a status of 503 (Service Unavailable) avec localtunnel. 
Je n'arrive toujours pas à le résoudre et c'est ma première fois de l'utiliser.
J'aurai besoin d'aide si possible ! 
Merci d'avance !
