### ISSUE TITLE
`next start` with Localtunnel throws a `504 Gateway Timeout` error

### ISSUE THREAD

**Issue by aquapi** [localtunnel/localtunnel#523] opened 2022-08-31 04:25 UTC
I'm using this code to start `next` with `localtunnel`:
```typescript
#!/usr/bin/env node

const { exec } = require("child_process");

function execute(command, name, cb = (() => { })) {
    const proc = exec("npx " + command, cb);

    proc.stderr.on('data', d => console.error(`[${name}]`, d));
    proc.stdout.on('data', d => console.log(`[${name}]`, d));

    return proc;
}

execute("next build", "Build",
    () =>
        execute("next start", "Start")
);
execute("lt --port 3000 --subdomain rnd-sq", "Share");

```

The server and the tunnel start just fine but the page does not respond for a while and throws a `504 Gateway Timeout`.
Do you have any solution?

**Comment by TheBoroer** [comment] 2023-05-17 14:06
This may have been caused by an intermittent server problem on my end a while back. 
I'll close this for now but lmk if it's still happening and i'll re-open and take a look

**Closed as completed by TheBoroer** 2023-05-17 14:06 UTC
