### ISSUE TITLE
things working fine till now localtunnel is not even starting

### ISSUE THREAD

**Issue by hardik7290** [localtunnel/localtunnel#335] opened 2019-12-14 15:25 UTC
things working fine till now localtunnel is not even starting and look like it got stuck

and i waited about 15 minutes and long.

![image](https://user-images.githubusercontent.com/19410263/70850765-08466880-1eb4-11ea-9ddc-f2423deb159d.png)

what happen?

**Comment by hardik7290** [comment] 2019-12-14 15:37
same issue closed #322 and i try ngrock for testing and it worked

**Comment by thesunRider** [comment] 2019-12-15 13:16
Same with me the screen goes blank

**Comment by MatissJanis** [comment] 2019-12-16 13:22
The server is still unresponsive :(

**Comment by dariatsenter** [comment] 2019-12-16 20:25
Same for me :(

**Comment by benheb** [comment] 2019-12-16 21:24
Same...

**Comment by smithki** [comment] 2019-12-16 22:58
Same here :(

**Comment by vensauro** [comment] 2019-12-16 23:43
Hello, the problem is with the certificate, see the solution in the issue #332 
```
$ lt -p 8000 -h http://localtunnel.me --local-https false
```

**Comment by vlatri** [comment] 2019-12-18 08:47
bump.

**Comment by proflinksgh** [comment] 2019-12-25 12:57
Same issue here oo.... Currently on ngrok but session terminates every 7hrs

**Comment by GeorgeWillaman** [comment] 2019-12-28 08:01
Bump.. Still not working for me

**Comment by noriellecruz** [comment] 2019-12-28 19:32
Is this issue will ever be fixed? The author seems to be inactive for long.

**Comment by GeorgeWillaman** [comment] 2019-12-28 19:59
For all interested, I've moved over to https://holepunch.io/
Working great for me for the time being (+ positive is I can reserve and use subdomains of my choosing)

**Comment by adis-io** [comment] 2019-12-30 05:29
> Hello, the problem is with the certificate, see the solution in the issue #332
> 
> ```
> $ lt -p 8000 -h http://localtunnel.me --local-https false
> ```

If you need https, you can use @Pirngruber's server temporarily:
```
lt -p 8000 -h https://tunnel.datahub.at
```

**Comment by uditalias** [comment] 2020-01-22 11:23
still not working with:
`lt -p 8080 -h http://localtunnel.me --local-https false`

**Comment by yohane55** [comment] 2020-01-24 11:03
https://localtunnel.me/ is down as of now. :(

**Comment by smithki** [comment] 2020-01-24 18:36
Is this the end? 😢

**Comment by lozzoc** [comment] 2020-01-27 20:21
> same issue closed #322 and i try ngrock for testing and it worked


uhh im developing web app and ngrok did not work for. i kept getting errorslike "wrong host headers"

farewell localtunnel! looks like we reached theend.

**Comment by Pirngruber** [comment] 2020-02-02 19:34
localtunnel.me is now up and running again :)
i took over the hosting and maintenance part from @defunctzombie so feel free to use it as before.

let us know if you have further questions

**Comment by DannyvanderJagt** [comment] 2020-02-18 13:06
@Pirngruber It down again. Any plans on making it more stable and do something about the uptime?

**Comment by cjancsar** [comment] 2020-03-25 19:16
Ah, that is why this library doesn't work....

**Comment by wrabit** [comment] 2020-05-23 08:07
down and out

**Comment by lozzoc** [comment] 2020-05-23 17:09
I used to use localtunnel to test out my web sites on my mobile and desktop devices, but now i just use the proxy in package.json with my react project, and use the local ip 10.0.0.27. How else have people used to use localtunnel?

**Comment by DavidOlawale** [comment] 2020-05-23 17:18
I had the same issue, localtunnel no longer works, you can try ngrok

**Comment by TheBoroer** [comment] 2020-09-06 00:11
I am now hosting localtunnel.me for this project so it should work like before. The only difference is that I'm handing out subdomains under the domain *.loca.lt instead of *.localtunnel.me (that's because I don't have full DNS control and without it can't get a free wildcard cert for the domain without). Let me know if you run into any issues.

**Comment by TheBoroer** [comment] 2020-10-15 00:06
@defunctzombie feel free to close this issue.

**Closed** 2020-10-18 15:00 UTC
